rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.about, name='about'),
        url(r'^add_category/$', views.add_category, name='add_category'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
#         url(r'^register/$', views.register, name='register'),
#         url(r'^login/$', views.user_login, name='login'),
        url(r'^restricted/', views.restricted, name='restricted'),
#         url(r'^logout/$', views.user_logout, name='logout'),
#        url(r'^search/$', views.search, name='search'),
        url(r'^goto/$', views.track_url, name='goto'),
        url(r'^like_category/$', views.like_category, name='like_category'),
        url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
        url(r'^category_search/$', views.category_search, name='category_search'),
        url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
        url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
        url(r'^change_password/$', views.change_password, name='change_password'),
        url(r'^users_profiles/$', views.users_profiles, name='users_profiles'),
)

tangowithdjango/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from rango.forms import UserProfileForm
from rango.models import UserProfile

# Create a new class that redirects the user to the index page, if successful at logging      
class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        profile = UserProfile(user=user)

        if 'website' in request.POST:
            profile.website = request.POST["website"]
        if 'picture' in request.FILES:
            profile.picture = request.FILES["picture"]
            print profile.picture
        profile.save()
        return '/rango/'
    
urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls')),
        #Add in this url pattern to override the default pattern in accounts.
    url(r'^accounts/register/$', MyRegistrationView.as_view(form_class=UserProfileForm), name='registration_register'),
    (r'^accounts/', include('registration.backends.simple.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
import os

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

def file_rename(instance, filename):
        name, extension = os.path.splitext(filename)
        upload_path = 'profile_images'
        filename = "%s_%s%s" % (instance.user.pk, instance.user.username, extension)
        return os.path.join(upload_path, filename)

class UserProfile(models.Model):
    # Change name of the uploaded file    
    
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to=file_rename, blank=True,default='profile_images/default.png')

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

rango/forms.py
from django import forms
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile
from rango.models import Page, Category
from registration.forms import RegistrationForm
from registration.models import RegistrationProfile
from django.contrib.auth.middleware import AuthenticationMiddleware


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them...
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,

        exclude = ('category',)
        #or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(RegistrationForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

rango/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render

from rango.bing_search import run_query
from rango.forms import CategoryForm
from rango.forms import PageForm
from rango.models import Category, UserProfile
from rango.models import Page


def index(request):
    # Query the database for a list of ALL categories currently stored.
    # Order the categories by no. likes in descending order.
    # Retrieve the top 5 only - or all if less than 5.
    # Place the list in our context_dict dictionary which will be passed to the template engine.
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    # Get the number of visits to the site.
    # We use the COOKIES.get() function to obtain the visits cookie.
    # If the cookie exists, the value returned is casted to an integer.
    # If the cookie doesn't exist, we default to zero and cast that.
    visits = request.session.get('visits')
    if not visits:
        visits = 1
    reset_last_visit_time = False

    last_visit = request.session.get('last_visit')
    if last_visit:
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        if (datetime.now() - last_visit_time).days > 0:
            # ...reassign the value of the cookie to +1 of what it was before...
            visits = visits + 1
            # ...and update the last visit cookie, too.
            reset_last_visit_time = True
    else:
        # Cookie last_visit doesn't exist, so create it to the current date/time.
        reset_last_visit_time = True

    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits
    context_dict['visits'] = visits


    response = render(request,'rango/index.html', context_dict)

    return response

def about(request):

    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage is the same as {{ boldmessage }} in the template!
    context_dict = {'standardmessage': "This tutorial has been put together by Enzo Roiz, 2161561."}
    
    # If the visits session varible exists, take it and use it.
    # If it doesn't, we haven't visited the site so set the count to zero.
    if request.session.get('visits'):
        visits = request.session.get('visits')
    else:
        visits = 0
    
    context_dict['visits'] = visits

    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.

    return render(request, 'rango/about.html', context_dict)

def category(request, category_name_slug):

    # Create a context dictionary which we can pass to the template rendering engine.
    context_dict = {}
   
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name
        
        # Count the category views
        try:
            category.views = category.views + 1
            category.save()
        except:
                pass

        # Retrieve all of the associated pages.
        # Note that filter returns >= 1 model instance.
        pages = Page.objects.filter(category=category).order_by('-views')
        
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category

        #Category Slug
        context_dict['category_slug'] = category.slug

    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything - the template displays the "no category" message for us.
        pass

    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)

            # Now call the index() view.
            # The user will be shown the homepage.
            return index(request)
        else:
            # The supplied form contained errors - just print them to the terminal.
            print form.errors
    else:
        # If the request was not a POST, display the form to enter details.
        form = CategoryForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):

    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
                cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                # probably better to use a redirect here.
                return category(request, category_name_slug)
        else:
            print form.errors
    else:
        form = PageForm()

    context_dict = {'form':form, 'category': cat}

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://', prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

    return render(request, 'rango/add_page.html', context_dict)

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

def track_url(request):
    page_id = None
    url = '/rango/'
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views = page.views + 1
                page.save()
                url = page.url
            except:
                pass

    return redirect(url)

@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']

    likes = 0
    if cat_id:
        cat = Category.objects.get(id=int(cat_id))
        if cat:
            likes = cat.likes + 1
            cat.likes =  likes
            cat.save()

    return HttpResponse(likes)

def suggest_category(request):
    
    def get_category_list(max_results=0, starts_with=''):
        cat_list = Category.objects.all()
        if starts_with:
            cat_list = Category.objects.filter(name__istartswith=starts_with)

        if max_results > 0:
            if len(cat_list) > max_results:
                cat_list = cat_list[:max_results]

        return cat_list

    starts_with = ''
    catid = None
    act_cat = None
    
    if request.method == 'GET':
        starts_with = request.GET['suggestion']
        if request.GET['catid'] != '':
            catid = request.GET['catid']
            act_cat = Category.objects.get(id=catid)
            
    cats = get_category_list(8, starts_with)
    
    return render(request, 'rango/cats.html', {'cats': cats, 'act_cat': act_cat })

def category_search(request):
    context_dict = {}
    context_dict['result_list'] = None 
    context_dict['query'] = None
    print "HERE WE ARE"
    if request.method == 'GET':
        query = request.GET['query'].strip()
        print "HERE WE GO"
        if query:
            # Run our Bing function to get the results list!
            result_list = run_query(query)

            context_dict['result_list'] = result_list
            context_dict['query'] = query
    print "AFTER ALL"
    
    return render(request, 'rango/category_search.html', context_dict)

@login_required
def profile(request, username):
    act_user = User.objects.get(username=username)
    userprofile, created = UserProfile.objects.get_or_create(user=act_user)
    
    if request.method == 'POST':
        if 'is_password' in request.POST:
            print "IS_PASSWORD"
            data = {}
            if 'old_password' in request.POST:
                data['old_password'] = request.POST['old_password']
            if 'new_password1' in request.POST:
                data['new_password1'] = request.POST['new_password1']
            if 'new_password2' in request.POST:
                data['new_password2'] = request.POST['new_password2']
            form = PasswordChangeForm(act_user, data)
            if form.is_valid():
                form.save(commit=True)
                act_user.save()
                user = authenticate(username=username, password=data['new_password1'])
                login(request, user)
                messages.success(request, 'Password changed.')
                print messages

templates/rango/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}
<div class="page-header">
	<h1>About</h1>
</div>
<div>
	<h1>Rango says...</h1>
	This is the about page!<br />
	{{ standardmessage }}</br>
	<p><strong>Visits: {{ visits }}</strong> </p>
	<img src="{% static "images/enzo.jpg" %}" alt="Enzo Roiz" />
</div>

{% endblock %}

templates/rango/add_category.html
{% extends 'base.html' %}

{% block title %}Add category{% endblock %}

{% block body_block %}
<div class="page-header">
	<h1>Add a category</h1>
</div>

<form role="form"  id="category_form" method="post" action="{% url 'add_category' %}">

    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br/>
        {{ field }}<br/>
    {% endfor %}
	<br/>
    <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
</form>

{% endblock %}

templates/rango/add_page.html
{% extends 'base.html' %}

{% block title %}Add page{% endblock %}

{% block body_block %}

<div class="page-header">
	<h1>Add a page to {{category.name}} category!</h1>
</div>

<form role="form"  id="page_form" method="post" action="{% url 'add_page'  category.slug %}">
<h2 class="form-signin-heading">Add a Page to <a href="{% url 'category'  category.slug %}"> {{ category.name }}</a></h2>
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br/>
        {{ field }}<br/>
    {% endfor %}
	<br/>
    <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
</form>

{% endblock %}

templates/rango/category.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
<div class="page-header">
	<h1>{{ category_name }}</h1>
</div>

	{% if user.is_authenticated %}
	     <!-- Display the search form elements here -->
	     <p><input class="form-control" type="text" style="width: 300px;" name="query" value="{{category_name}}" id="query" /></p>
	     <input id="search" class="btn btn-primary" type="submit" name="submit" value="Search" />
		<br/>
		<br/>
    {% endif %}
    
    {% if category %}
        {% if pages %}
        		<ul>
                {% for page in pages %}
                	<li>
                	<a href="{% url 'goto' %}?page_id={{page.id}}">{{ page.title }}</a>
        			{% if page.views > 1 %}
            			({{ page.views }} views)
            		{% elif page.views == 1 %}
            			({{ page.views }} view)
       				{% endif %}
       				</li>
                {% endfor %}
                </ul>
        {% else %}
                <strong>No pages currently in category.</strong><br/>
    {% endif %}
    
    <p>
    {% if user.is_authenticated %}
	        <button id="likes" data-catid="{{category.id}}" class="btn btn-primary" type="button">
	        	<span class="glyphicon glyphicon-thumbs-up"></span>
	        	Like
	        </button>
	{% endif %}
	<strong id="like_count">{{ category.likes }}</strong> people like this category<br/>
	</p>

        {% if user.is_authenticated %}
	        <a href="{% url 'add_page' category.slug %}">Add a Page</a>
	        {% endif %}
        {% else %}
	        The specified category {{ category_name }} does not exist!<br/>
	        Did you look at the right place?<br/>
	        <a href="{% url 'index' %}">Click to go back to the Home page!</a><br />
	        <img src="{% static "images/rango_cat_not_found.jpg" %}" alt="Picture of Rango" />
	    {% endif %}
	    <br/>
	    <br/>
	    <p>Category views: {{ category.views }}</p>
		
		<div id="category_search"></div>
{% endblock %}

templates/rango/category_search.html
<div class="panel">
	{% if result_list %}
	<div class="panel-heading">
		<h3 class="panel-title">Results</h3>
		<!-- Display search results in an ordered list -->
		<div class="panel-body">
			<div class="list-group">
				{% for result in result_list %}
				<div class="list-group-item">
					<h4 class="list-group-item-heading">
						<a href="{{ result.link }}">{{ result.title }}</a>
					</h4>
					<p class="list-group-item-text">{{ result.summary }}</p>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
	{% else %}
		<p>Results not found for your search. Check your typing or try to be less specific.</p>
	{% endif %}
</div>

templates/rango/cats.html
<ul class="nav nav-sidebar" id="nav-sidebar">
{% if cats %}
    {% for c in cats %}
    	{% if c == act_cat %} <li  class="active" > {% else  %} <li>{% endif %}
        	<a href="{% url 'category'  c.slug %}">{{ c.name }}</a></li>
	{% endfor %}

{% else %}
    <li class="disabled"><a href="#">There are no categories.</a></li>
{% endif %}
</ul>

templates/rango/change_password.html
<form id="change_password_form" role="form" method="post" action=".">
	{% csrf_token %}
	
	{% for error in form.non_field_errors %}
		<p>{{error}}</p>
	{% endfor %}
	
	{% if form.old_password.errors %}
	<div class="form-group has-warning has-feedback">
		<p class="required">
			<label for="id_old_password">Password:</label> <input
				class="form-control" id="id_old_password" name="old_password"
				type="password" placeholder="{% for error in form.old_password.errors %}{{ error }} {% endfor %}" />
		</p>
	</div>
	{% else %}
	<div class="form-group">
		<p class="required">
			<label for="id_old_password">Password:</label> <input
				class="form-control" id="id_old_password" name="old_password"
				type="password" placeholder="Enter your password" />
		</p>
	</div>
	{% endif %}
	
	{% if form.new_password1.errors %}
	<div class="form-group has-warning has-feedback">
		<p class="required">
			<label for="id_new_password1">Password:</label> <input
				class="form-control" id="id_new_password1" name="new_password1"
				type="password" placeholder="{% for error in form.new_password1.errors %}{{ error }} {% endfor %}" />
		</p>
	</div>
	{% else %}
	<div class="form-group">
		<p class="required">
			<label for="id_new_password1">Password:</label> <input
				class="form-control" id="id_new_password1" name="new_password1"
				type="password" placeholder="Enter your new password" />
		</p>
	</div>
	{% endif %}
	
	{% if form.new_password2.errors %}
	<div class="form-group has-warning has-feedback">
		<p class="required">
			<label for="id_new_password2">Password (again):</label> <input
				class="form-control" id="id_new_password2" name="new_password2"
				type="password" placeholder="{% for error in form.new_password2.errors %}{{ error }} {% endfor %}" />
		</p>
	</div>
	{% else %}
	<div class="form-group">
		<p class="required">
			<label for="id_new_password2">Password (again):</label> <input
				class="form-control" id="id_new_password2" name="new_password2"
				type="password" placeholder="Enter your new password again" />
		</p>
	</div>
	{% endif %}
	
	<input type="hidden" id="id_is_password" name="is_password" value="True">
	
	<input id="save_password" class="btn btn-primary" type="submit" name="submit" value="Confirm" />
 	
	<input id="cancel_password" class="btn btn-primary" type="button" name="cancel" value="Cancel" />
</form>

templates/rango/edit_profile.html
<form id="edit_form" role="form" method="post" action="." enctype="multipart/form-data">
	{% csrf_token %}
	
	{% for error in form.non_field_errors %}
		<p>{{error}}</p>
	{% endfor %}
	
	{% if form.email.errors %}
	<div class="form-group has-warning has-feedback">
		<p class="required">
			<label for="id_email">E-mail:</label> <input class="form-control"
				id="id_email" name="email" type="email" placeholder="{% for error in form.email.errors %}{{ error }} {% endfor %}" />
		</p>
	</div>
	{% else %}
	<div class="form-group">
		<p class="required">
			<label for="id_email">E-mail:</label> <input class="form-control"
				id="id_email" name="email" type="email" placeholder="Enter email" value="{{user.email}}" />
		</p>
	</div>
	{% endif %}
		
	{% if form.website.errors %}
	<div class="form-group has-warning has-feedback">
		<p class="required">
			<label for="id_website">Website:</label> <input
				class="form-control" id="id_website" name="website"
				type="url" placeholder="{% for error in form.website.errors %}{{ error }} {% endfor %}" />
		</p>
	</div>
	{% else %}
	<div class="form-group">
		<p class="required">
			<label for="id_website">Website:</label> <input
				class="form-control" id="id_website" name="website"
				type="url" placeholder="Website" value="{{userprofile.website}}"/>
		</p>
	</div>
	{% endif %}
	
	<input id="id_picture" name="picture" type="file" class="btn btn-file btn-default"><br/>
	
	<input id="save" class="btn btn-primary" type="submit" name="submit" value="Save Changes" />
 	
	<input id="cancel" class="btn btn-primary" type="button" name="cancel" value="Cancel" />
</form>

templates/rango/index.html
{% extends 'base.html' %} 

{% load staticfiles %} 

{% block title%} Index {% endblock %} 

{% block body_block %} 

<div class="page-header">
{% if user.is_authenticated %}
	<h1>Rango says... hello {{ user.username }}!</h1>
{% else %}
	<h1>Rango says... hello world!</h1>
{% endif %}
</div>

<div class="row placeholders">
	<div class="col-xs-12 col-sm-6 placeholder">
		<div class="panel panel-primary">
    		<div class="panel-heading">
				<h3>Categories</h3>
			</div>
		</div>
		{% if categories %}
		<ul class="list-group">
			{% for category in categories %}
				<li class="list-group-item"><a href="{% url 'category'  category.slug %}">{{ category.name }}</a>
				{% if category.likes > 1 %}
           			({{ category.likes }} likes)
           		{% elif category.likes == 1 %}
           			({{ category.likes }} like)
   				{% endif %}
				</li> 
			{% endfor %}
		</ul>
		{% else %} <strong>There are no categories present.</strong> {% endif %}

	</div>
	<div class="col-xs-12 col-sm-6 placeholder">
		<div class="panel panel-primary">
    		<div class="panel-heading">
					<h3>Pages</h3>
			</div>
		</div>
		{% if pages %}
		<ul class="list-group">
			{% for page in pages %}
				<li class="list-group-item">
				<a href="{% url 'goto' %}?page_id={{page.id}}">{{ page.title }}</a>
				{% if page.views > 1 %}
           			({{ page.views }} views)
           		{% elif page.views == 1 %}
           			({{ page.views }} view)
   				{% endif %}
				</li> 
			{% endfor %}
		</ul>
		{% else %} <strong>There are no categories present.</strong> {% endif %}
	</div>

</div>

<p>Visits: {{ visits }}</p>
{% endblock %}

templates/rango/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block body_block %}

<h1>Login to Rango</h1>

<form id="login_form" method="post" action="{% url 'login' %}">
    {% csrf_token %}

    <p>Username: <input type="text" name="username" value="" size="50" /></p>

    <p>Password: <input type="password" name="password" value="" size="50" /></p>

    <p>{{ invalid_login }}</p>
    <input type="submit" name="submit" value="Login" />
</form>

{% endblock%}

templates/rango/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block body_block %}

<h1>Register with Rango</h1>

{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'index' %}">Return to the homepage.</a><br />
{% else %}
Rango says: <strong>register here!</strong><br />

<form id="user_form" method="post" action="{% url 'register' %}"
        enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form. The as_p method wraps each element in a paragraph
         (<p>) element. This ensures each element appears on a new line,
         making everything look neater. -->
    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}

{% endblock %}

templates/rango/restricted.html
{% extends 'base.html' %}

{% block title %}Restricted Page{% endblock %}

{% block body_block %}

<h2>"Since you're logged in, you can see this text!"</h2>

{% endblock %}

templates/rango/search.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Search{% endblock %}

{% block body_block %}

    <div class="page-header">
        <h1>Search with Rango</h1>
    </div>

    <div class="row">

        <div class="panel panel-primary" style="padding:10px">
            <br/>

            <form class="form-inline" id="user_form" method="post" action="{% url 'search' %}">
                {% csrf_token %}
                <!-- Display the search form elements here -->
                <input class="form-control" type="text" size="50" name="query" value="" id="query" />
                <input class="btn btn-primary" type="submit" name="submit" value="Search" />
                <br />
            </form>

            <div class="panel">
                {% if result_list %}
                    <div class="panel-heading">
                    <h3 class="panel-title">Results</h3>
                    <!-- Display search results in an ordered list -->
                    <div class="panel-body">
                        <div class="list-group">
                            {% for result in result_list %}
                                <div class="list-group-item">
                                    <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}</a></h4>
                                    <p class="list-group-item-text">{{ result.summary }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                </div>
            </div>
 </div>

{% endblock %}

templates/rango/users_profiles.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Users Profiles{% endblock %}

{% block body_block %}
<div class="page-header">
	<h1>Users Profiles</h1>
</div>

<div class="panel">
	{% if user_list %}
	<div class="panel-heading">
		<!-- Display search results in an ordered list -->
		<div class="panel-body">
			<div class="list-group">
				{% for listuser in user_list %}
				<div class="list-group-item">
					<h4 class="list-group-item-heading">
						<a href="{% url 'profile' listuser.username %}">{{ listuser.username }}</a>
					</h4>
					<p class="list-group-item-text">E-mail:{{ listuser.email }}</p>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
	{% else %}
		<p>There are no users for the site.</p>
	{% endif %}
</div>
{% endblock %}